[package]
name = "wasm_runner"
version = "0.1.0"
authors = ["oooooba <fuumin.23@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wast = "21.0.0"
